### PR TITLE
add annotations support to deployment and service

### PR DESCRIPTION
**Pull request by ahmadiq**

### CODE REVIEW

**Review by kahootali — DISMISSED** [review]

**Comment by stakater-user** [comment]
@ahmadiq [Build 1](https://jenkins.cicd-tools.stackator.com/job/Stakater%20Charts/job/kubernetes-dashboard-1-7/job/PR-1/1/) has Failed!

**Comment by stakater-user** [comment]
@ahmadiq [Build 3](https://jenkins.cicd-tools.stackator.com/job/Stakater%20Charts/job/kubernetes-dashboard-1-7/job/PR-1/3/) has Failed!

**Comment by stakater-user** [comment]
@ahmadiq [Build 4](https://jenkins.cicd-tools.stackator.com/job/Stakater%20Charts/job/kubernetes-dashboard-1-7/job/PR-1/4/) has Failed!

**Comment by stakater-user** [comment]
@ahmadiq Chart: kubernetes-dashboard-1-7 Dry Run successful

**Review by kahootali — APPROVED** [review]

**Pull request merged**
